import Head from 'next/head'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faEnvelope, faCalendar } from '@fortawesome/free-regular-svg-icons'
import BouncyButton from '@/components/bouncyButton'
// import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'

// const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  return (
    <>
      <Head>
        <title>Flavourdeck</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Welcome to Flavourdeck!</h1>

        <BouncyButton shouldBounceEval={() => { return true }} className='primary'>
          Start cooking
        </BouncyButton>
      </main>
    </>
  )
}
