import BouncyButton from '@/components/bouncyButton';
import { User } from 'firebase/auth';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useState } from 'react';



export default function Home() {
  const [localUser, setLocalUser] = useState<User | null>(null);
  
  const router = useRouter();
  function push(path: string) { router.push(path) }
  return (
    <>
      <Head>
        <title>Flavourdeck</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Welcome to Flavourdeck</h1>

        {/* <button className='primary' onClick={() => {push('/recipe/new')}}> Start cooking </button> */}
        {/* <BouncyButton shouldBounceEval={() => { return true }}  className='primary'>
          Start cooking
        </BouncyButton> */}
        <button className='primary' style={{backgroundColor: '#FFC857', color: 'black'}} onClick={() => { push('/settings') }}>Settings</button>
        <button className='primary' style={{backgroundColor: '#5B869D'}} onClick={() => { push('/settings') }}>Settings</button>
        <button className='primary' style={{backgroundColor: '#62A56B'}} onClick={() => { push('/settings') }}>Settings</button>
        <button className='primary' style={{backgroundColor: '#EF6461'}} onClick={() => { push('/settings') }}>Settings</button>
        <button className='primary' style={{backgroundColor: '#E6476C'}} onClick={() => { push('/settings') }}>Settings</button>
      </main>
    </>
  )
}