import BouncyButton from '@/components/bouncyButton';
import { User } from 'firebase/auth';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useState } from 'react';
import log from '../api/log';
import { listenForUser } from '../api/users/functions';



export default function Home() {
  const [localUser, setLocalUser] = useState<User | null>(null);
  listenForUser((user) => {
    if (!user) {
      log("User is null! Redirecting to login page", "settings/listenForUser");
      router.push({
        pathname: "/login",
        query: {
          then: "/settings",
          thenDisplayName: "Settings",
        },
      });
    } else {
      setLocalUser(user);
      log("User signed in. Continuing...", "settings/listenForUser");
    }
  });
  const router = useRouter();
  function push(path: string) { router.push(path) }
  return (
    <>
      <Head>
        <title>Flavourdeck</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Welcome to Flavourdeck</h1>

        <BouncyButton shouldBounceEval={() => { return true }} className='primary' onClick={() => { push('/recipe/new') }}> Start cooking </BouncyButton>
        {/* <BouncyButton shouldBounceEval={() => { return true }}  className='primary'>
          Start cooking
        </BouncyButton> */}
        <button className='primary' onClick={() => { push('/settings') }}>Settings</button>
      </main>
    </>
  )
}
