import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import log from './api/log';

export default function UserSettings() {
  const router = useRouter();
  const { uid } = router.query;
  const [user, setUser] = useState(null);
  const [email, setEmail] = useState(null);
  const [name, setName] = useState(null);


  useEffect(() => {
    // This code will only run on the client-side
    const storedUser = localStorage.getItem('user');
    if (storedUser) {
      setUser(JSON.parse(storedUser));
    } else {
      router.push('/login');
    }
  }, []);
  
  /**
   * Updates the user settings
   * @returns {void}
   */
  function updateSettings() {
    log("Updating user settings", "settings/updateSettings")
    if (name == null) { let name = user.displayName}
    if (email == null) { let email = user.email}
    let newSettings = {
      name: name,
      email: email,
    }
    localStorage.setItem('user', JSON.stringify(newSettings));
  }

  log("Rendering user settings page for user with uid " + uid, "settings")

  return (
    <>
      <Head>
        <title>Flavourdeck</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Settings - {user ? user.email : 'No user logged in'}</h1>
        <p>UID: {uid}</p>
        <h2>User profile:</h2>
        <p>Name: {user ? user.displayName : "Unknown"}</p>
        <input type="text" placeholder="Change your name" />
        <br />
        <p>Email: {user ? user.email : "unknown email"}</p>
        <input type="text" placeholder="Change your email" />
        <br />
        <p>Profile picture:</p>
        <input type="file"/>
        <br />
        <button className="primary" onClick={updateSettings}>Save</button>
      </main>
    </>
  )
}