import Head from 'next/head';
import { useRouter } from 'next/router';
import { logoutUser } from '../../api/users/functions';



export default function Logout() {
    const router = useRouter();
    async function logUserOut() {
        await logoutUser();
        router.push('/');
    }
    logUserOut();
  return (
    <>
      <Head>
        <title>Logout | Flavourdeck</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Logging out... </h1>

      </main>
    </>
  )
}
