name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node
      uses: actions/setup-node@v4.0.0

    - name: Install dependencies
      run: yarn && yarn add vercel

    - name: Add firefile 
      run: echo ${{ secrets.FIREFILE}} >> ./firebase.json

    - name: Build
      run: yarn run build

    - name: Deploy
      run: vercel --token ${{ secrets.VERCEL_AUTH }}

